export default interface Product {
  TestMode?: boolean;
  ProductID?: number;
  ManufacturerID?: number;
  ItemID?: string;
  ItemName?: string;
  Description?: string;
  Notes?: string;
  Dimensions?: string;
  BasePrice?: number;
  SpecialPrice?: number;
  OrderMinimumQuantity?: number;
  ContainerMinQty?: number;
  OrderMultipleQuantity?: number;
  OnHandQuantity?: number;
  Category?: string | null;
  IntroDate?: string;
  BackOrderDate?: string;
  UPC?: string;
  PriceLevel1?: number;
  PriceLevel2?: number;
  PriceLevel3?: number;
  PriceLevel4?: number;
  PriceLevel5?: number;
  PriceLevel6?: number;
  PriceLevel7?: number;
  PriceLevel8?: number;
  PriceLevel9?: number;
  PieceBox?: string | null;
  Cubes?: number;
  UnitOfMeasure?: string;
  UDF1?: string;
  UDF2?: string;
  UDF3?: string;
  UDF4?: string;
  UDF5?: string;
  AdditionalImageCount?: number | null;
  PhotoName?: string;
  AppendProductModifiers?: boolean;
  Discontinued?: boolean;
  CreatedOn?: string;
  CreatedBy?: string | null;
  ModifiedOn?: string | null;
  ModifiedBy?: string | null;
  DeletedOn?: string | null;
  DeletedBy?: string | null;
  IsDeleted?: boolean;
  PriceLevel10?: boolean;
  PriceLevel11?: boolean;
  PriceLevel12?: boolean;
  PriceLevel13?: boolean;
  PriceLevel14?: boolean;
  PriceLevel15?: boolean;
  PriceLevel16?: boolean;
  PriceLevel17?: boolean;
  PriceLevel18?: boolean;
  PriceLevel19?: boolean;
  PriceLevel20?: boolean;
  Weight?: number;
  DimensionsMetric?: string | null;
  Source?: string;
  InventoryStatus?: string | null;
  CategoryIDs?: string | null;
  CatalogCode?: string;
  CatalogName?: string;
  udf6?: string;
  udf7?: string;
  udf8?: string;
  udf9?: string;
  udf10?: string;
  udf11?: string;
  udf12?: string;
  udf13?: string;
  udf14?: string;
  udf15?: string;
  udf16?: string;
  udf17?: string;
  udf18?: string;
  udf19?: string;
  udf20?: string;
  reportCategory?: string;
  additionalPhotos?: string;
  showRelatedFor?: string | null;
  showChildFor?: string | null;
}
